name: Update library in gen-pack scripts
on:
  workflow_dispatch:
  schedule:
    - cron: "30 9 * * *"

permissions:
  contents: write
  pull-requests: write

jobs:
  update-workflows:
    uses: Open-CMSIS-Pack/gen-pack/.github/workflows/update-lib.yml@update-scripts-workflow
    secrets:
      TOKEN_ACCESS: ${{ secrets.TOKEN_WORKFLOW_UPDATE }}
